/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conexion.Conexion;
import controlador.VehiculoControlador;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Vehiculo;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALEJANDRO
 */
public class MenuFrom extends javax.swing.JFrame {

    private int idVehiculo = 0;

    public MenuFrom() {
        initComponents();
        this.setTitle("Sistema de Parqueadero");
        this.setSize(900, 550);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //cargar tabla vehiculos
        this.CargarTablaVehiculos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Logo = new javax.swing.JLabel();
        jToggleButton_cerrar_sesion = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_footer = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_registrar_vehiculo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton_ingresar_vehiculo = new javax.swing.JButton();
        jComboBox_tipo_vehiculo = new javax.swing.JComboBox<>();
        jTextField_Propietario = new javax.swing.JTextField();
        jTextField_Placa = new javax.swing.JTextField();
        jPanel_retirar_vehiculo = new javax.swing.JPanel();
        jPanel_administrar_vehiculo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_fecha_busqueda = new javax.swing.JLabel();
        jTextField_busqueda_criterio = new javax.swing.JTextField();
        jDateChooser_fecha_bucar = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_vehiculos = new javax.swing.JTable();
        jButton_buscar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("SISTEMA DE PARQUEADERO");

        jLabel_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estacionamiento.png"))); // NOI18N
        jLabel_Logo.setAlignmentX(0.5F);
        jLabel_Logo.setAutoscrolls(true);

        jToggleButton_cerrar_sesion.setBackground(new java.awt.Color(0, 102, 102));
        jToggleButton_cerrar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        jToggleButton_cerrar_sesion.setText("CERRAR SESION");
        jToggleButton_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_cerrar_sesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton_cerrar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jToggleButton_cerrar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 550));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel_footer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_footer.setText("@ Desarrollado por Jhonatan Rojas, Alejandro Bonilla y Carol Acosta");
        jLabel_footer.setToolTipText("");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel_registrar_vehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Registro de Ingreso de Vehiculos al Parqueadero ");
        jPanel_registrar_vehiculo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Placa: ");
        jPanel_registrar_vehiculo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Propietario:");
        jPanel_registrar_vehiculo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Tipo de Vehiculo: ");
        jPanel_registrar_vehiculo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jButton_ingresar_vehiculo.setBackground(new java.awt.Color(0, 102, 0));
        jButton_ingresar_vehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ingresar_vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coche-revisado.png"))); // NOI18N
        jButton_ingresar_vehiculo.setText("INGRESAR VEHICULO");
        jButton_ingresar_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ingresar_vehiculoActionPerformed(evt);
            }
        });
        jPanel_registrar_vehiculo.add(jButton_ingresar_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 220, 30));

        jComboBox_tipo_vehiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox_tipo_vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Automovil", "Motocicleta", "Bicicleta" }));
        jComboBox_tipo_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipo_vehiculoActionPerformed(evt);
            }
        });
        jPanel_registrar_vehiculo.add(jComboBox_tipo_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 220, 30));

        jTextField_Propietario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PropietarioActionPerformed(evt);
            }
        });
        jPanel_registrar_vehiculo.add(jTextField_Propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 220, -1));

        jTextField_Placa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PlacaActionPerformed(evt);
            }
        });
        jTextField_Placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PlacaKeyPressed(evt);
            }
        });
        jPanel_registrar_vehiculo.add(jTextField_Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 220, -1));

        jTabbedPane1.addTab("Registrar Vehiculo", jPanel_registrar_vehiculo);

        jPanel_retirar_vehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_retirar_vehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Retirar Vehiculo", jPanel_retirar_vehiculo);

        jPanel_administrar_vehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administracion de  Vehiculos del parqueadero");
        jPanel_administrar_vehiculo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Placa/Propietario");
        jPanel_administrar_vehiculo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        jLabel_fecha_busqueda.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel_fecha_busqueda.setText("Fecha");
        jPanel_administrar_vehiculo.add(jLabel_fecha_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 50, 30));

        jTextField_busqueda_criterio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_busqueda_criterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_busqueda_criterioActionPerformed(evt);
            }
        });
        jPanel_administrar_vehiculo.add(jTextField_busqueda_criterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, 30));
        jPanel_administrar_vehiculo.add(jDateChooser_fecha_bucar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 120, 30));

        jTable_vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_vehiculos);

        jPanel_administrar_vehiculo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 580, 230));

        jButton_buscar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        jPanel_administrar_vehiculo.add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 40, 30));

        jTabbedPane1.addTab("Administrar Vehiculo", jPanel_administrar_vehiculo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_footer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel_footer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Administrar Vehiculo");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 650, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_cerrar_sesionActionPerformed
        LoginFrom cerrar = new LoginFrom();
        cerrar.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jToggleButton_cerrar_sesionActionPerformed

    private void jTextField_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PlacaActionPerformed

    private void jTextField_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PropietarioActionPerformed

    private void jComboBox_tipo_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipo_vehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tipo_vehiculoActionPerformed

    private void jButton_ingresar_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ingresar_vehiculoActionPerformed

        //BLOQUE DE CODIGO
        String placa = jTextField_Placa.getText().trim();
        String propietario = jTextField_Propietario.getText().trim();

        if (placa.isEmpty() || propietario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos");
        } else {
            String tipo_vehiculo = jComboBox_tipo_vehiculo.getSelectedItem().toString().trim();
            if (tipo_vehiculo.equalsIgnoreCase("Seleccione:")) {
                JOptionPane.showMessageDialog(null, "Seleccione el tipo de vehiculo");

            } else {

                VehiculoControlador VehiculoC = new VehiculoControlador();
                Vehiculo VehiculoM = new Vehiculo();

                VehiculoM.setPlaca(placa);
                VehiculoM.setPropietario(propietario);
                VehiculoM.setTipoVehiculo(tipo_vehiculo);

                //FECHA Y HORA DE ENTRADA DEL VEHICULO
                DateFormat FechaFormato = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                Calendar calendario = Calendar.getInstance();
                Date fecha = calendario.getTime();
                String Fecha = FechaFormato.format(fecha);

                VehiculoM.setHoraEntrada(Fecha);
                VehiculoM.setHoraSalida(null);
                VehiculoM.setEstado("INGRESADO");

                if (VehiculoC.guardar(VehiculoM)) {

                    JOptionPane.showMessageDialog(null, "Vehiculo ingresado correctamente");
                    //cargar la tabla vehiculos
                    this.CargarTablaVehiculos();

                    jTextField_Placa.setText("");
                    jTextField_Propietario.setText("");
                    //jComboBox_tipo_vehiculo.setSelectedItem("Seleccion:");
                    jComboBox_tipo_vehiculo.setSelectedIndex(0);

                } else {
                    JOptionPane.showMessageDialog(null, "Error al ingresar vehiculo");

                }
            }
        }
    }//GEN-LAST:event_jButton_ingresar_vehiculoActionPerformed

    private void jTextField_PlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PlacaKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_Propietario.requestFocus();
        }

    }//GEN-LAST:event_jTextField_PlacaKeyPressed

    private void jTextField_busqueda_criterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_busqueda_criterioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_busqueda_criterioActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed

        String PlacaPropietarioBusqueda = jTextField_busqueda_criterio.getText().trim();
        Date FechaBusqueda = jDateChooser_fecha_bucar.getDate();
        String FechaCadena = "";

        if (FechaBusqueda != null) {

            SimpleDateFormat smp = new SimpleDateFormat("yyyy/MM/dd");
            FechaCadena = smp.format(FechaBusqueda);
        }

        if (PlacaPropietarioBusqueda.isEmpty() && FechaCadena.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el propietario o la placa del vehiculo");
            this.CargarTablaVehiculos();

        } else {

            VehiculoControlador VehiculoCon = new VehiculoControlador();

            try {
                VehiculoCon.buscarVehiculosPlacasFecha(PlacaPropietarioBusqueda, FechaCadena);
            } catch (SQLException ex) {
                Logger.getLogger(MenuFrom.class.getName()).log(Level.SEVERE, null, ex);
            }
            ArrayList<Vehiculo> ListaVehiculo = VehiculoCon.listaVehiculo;

            DefaultTableModel model = new DefaultTableModel();

            this.jTable_vehiculos = new JTable(model);
            this.jScrollPane1.setViewportView(this.jTable_vehiculos);

            model.addColumn("N°1");
            model.addColumn("Placa");
            model.addColumn("Propietario");
            model.addColumn("Tipo de Vehiculo");
            model.addColumn("Valor Pagado");
            model.addColumn("Estado");

            Object fila[] = new Object[6];

            for (Vehiculo vehiculo : ListaVehiculo) {
                fila[0] = vehiculo.getIdVehiculo();
                fila[1] = vehiculo.getPlaca();
                fila[2] = vehiculo.getPropietario();
                fila[3] = vehiculo.getTipoVehiculo();
                fila[4] = vehiculo.getValorPagado();
                fila[5] = vehiculo.getEstado();
                model.addRow(fila);

            }
            
            jTextField_busqueda_criterio.setText("");
        }

    }//GEN-LAST:event_jButton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_ingresar_vehiculo;
    private javax.swing.JComboBox<String> jComboBox_tipo_vehiculo;
    private com.toedter.calendar.JDateChooser jDateChooser_fecha_bucar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_fecha_busqueda;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_administrar_vehiculo;
    private javax.swing.JPanel jPanel_registrar_vehiculo;
    private javax.swing.JPanel jPanel_retirar_vehiculo;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_vehiculos;
    private javax.swing.JTextField jTextField_Placa;
    private javax.swing.JTextField jTextField_Propietario;
    private javax.swing.JTextField jTextField_busqueda_criterio;
    private javax.swing.JToggleButton jToggleButton_cerrar_sesion;
    // End of variables declaration//GEN-END:variables

    //Metodo para mostrar todos los vehiculos registrados
 private void CargarTablaVehiculos() {
    Connection cn = Conexion.conectar();
    DefaultTableModel model = new DefaultTableModel();
    String sql = "select id_vehiculo, placa, propietario, tipo_vehiculo, valor_pagado, estado from vehiculos";
    Statement st;
    try {
        st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        this.jTable_vehiculos = new JTable(model);
        this.jScrollPane1.setViewportView(this.jTable_vehiculos);

        model.addColumn("N°"); // ID
        model.addColumn("Placa");
        model.addColumn("Propietario");
        model.addColumn("Tipo de Vehículo");
        model.addColumn("Valor Pagado");
        model.addColumn("Estado");

        while (rs.next()) {
            Object fila[] = new Object[6]; // Cambiado a tamaño 6
            for (int i = 0; i < 6; i++) { // Ajustado para recorrer solo 6 columnas
                fila[i] = rs.getObject(i + 1);
            }
            model.addRow(fila);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar los vehículos: " + e.getMessage());
        e.printStackTrace();
    }
}


    }


